services:
  hh515lm-reboot:
    image: ghcr.io/jandziaslo/hh515lm-reboot:latest
    pull_policy: always
    network_mode: host
    env_file:
      - .env
    command:
      - --monitor
    init: true
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
    security_opt:
      - no-new-privileges:true
